# fly.toml file generated for monet-pgs on 2023-02-13T12:08:48-08:00

app = "monet-pgs"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = "chipdelmal/monet-pgs:0.3.8"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [services.concurrency]
	hard_limit = 25
	soft_limit = 20

  [[services.tcp_checks]]
	grace_period = "1s"
	interval = "15s"
	port = "8000"
	restart_limit = 6
	timeout = "2s"