version: '3.8'
services:
  # web:
  #   image: chipdelmal/monet-cef:latest
  dashboard:
    build: 
      context: ./
    container_name: ${COMPOSE_PROJECT_NAME}_dashboard
    hostname: ${COMPOSE_PROJECT_NAME}_dashboard
    restart: always
    ports:
      - 5000:80
    networks:
      - network 
    
    
   
networks:
  network:
    driver: bridge